# Generated by Django 5.1.6 on 2025-06-29 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'timestamp'], name='Chat_messag_chat_id_8d6045_idx'),
        ),
    ]
