# Generated by Django 5.1.6 on 2025-03-21 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
        ('home', '0006_alter_product_seller_alter_productimages_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_product', to='home.product'),
        ),
    ]
