# Generated by Django 5.1.4 on 2025-01-12 12:54

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.user_directory_path),
        ),
    ]
