# Generated by Django 5.1.6 on 2025-06-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='showNumber',
            field=models.BooleanField(default=False),
        ),
    ]
