# Generated by Django 5.1.4 on 2024-12-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
