# Generated by Django 5.1.6 on 2025-06-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_shownumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='other_category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
