# Generated by Django 5.1.4 on 2025-02-04 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_views_product_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Views',
            new_name='views',
        ),
        migrations.CreateModel(
            name='Repoerted_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('offensive', 'Offensive Content'), ('fraud', 'Fraud'), ('duplicate', 'Duplicate Ad'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='home.product')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
