# Generated by Django 5.1.4 on 2024-12-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_customuser_date_of_birth_customuser_about_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catagory_icon_FS',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
