# Generated by Django 5.1.4 on 2025-01-04 17:49

import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_catagory_icon_fs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='used', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=home.models.user_directory_path)),
                ('image2', models.ImageField(upload_to=home.models.user_directory_path)),
                ('image3', models.ImageField(upload_to=home.models.user_directory_path)),
                ('image4', models.ImageField(upload_to=home.models.user_directory_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
