# Generated by Django 5.1.6 on 2025-09-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='ex',
            field=models.CharField(default='', max_length=25),
        ),
    ]
